parameters:
    sam_business_right.type.class: CanalTP\SamEcoreSecurityBundle\Form\Type\Permission\BusinessRightType

services:
    sam_business_right.type:
        class: '%sam_business_right.type.class%'
        arguments:
           - '@sam.business_component'
           - '@security.authorization_checker'
        tags:
            - { name: form.type, alias: sam_business_right }
