sam_role:
    path:  /
    defaults: { _controller: "CanalTPSamEcoreSecurityBundle:Role:index" }

sam_role_new:
    path:  /new
    defaults: { _controller: "CanalTPSamEcoreSecurityBundle:Role:new" }

sam_role_create:
    path:  /create
    defaults: { _controller: "CanalTPSamEcoreSecurityBundle:Role:create" }
    requirements: { attribute: post }

sam_role_edit:
    path:  /{id}/edit
    defaults: { _controller: "CanalTPSamEcoreSecurityBundle:Role:edit" }

sam_role_update:
    path:  /{id}/update
    defaults: { _controller: "CanalTPSamEcoreSecurityBundle:Role:update" }
    requirements: { attribute: post|put }

sam_role_delete:
    path:  /{id}/delete
    defaults: { _controller: "CanalTPSamEcoreSecurityBundle:Role:delete" }
    requirements: { attribute: post|delete|get }
