sam_security_business_right_edit:
    path: /business/right/edit
    defaults: { _controller: CanalTPSamEcoreSecurityBundle:BusinessRight:edit }

sam_security_business_right_edit_switch_app:
    path: /business/right/edit/switch/{application}
    defaults: { _controller: CanalTPSamEcoreSecurityBundle:BusinessRight:switchEditApp }
    requirements:
        applicationId: \d+
